# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
env:
  - GO111MODULE=on
builds:
- env:
  - CGO_ENABLED=0
  goos:
    - linux
    - darwin
    - windows
  goarch:
    - amd64
archives:
- name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
  replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    amd64: x86_64
  format_overrides:
  - goos: windows
    format: zip
nfpms:
- name_template: "{{ .ProjectName }}-{{ .Version }}.{{ .Arch }}"
  replacements:
    amd64: x86_64
  homepage:  https://soh.re
  description: Gather kubernetes capacity information
  maintainer: Jonathan Seth Mainguy <jon@soh.re>
  license: GPLv2
  vendor: Jmainguy
  formats:
  - deb
  - rpm
checksum:
  name_template: 'checksums.txt'
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
