apiVersion: authorization.openshift.io/v1
kind: ClusterRole
metadata:
  name: k8scapcity
rules:
- apiGroups:
  - ""
  attributeRestrictions: null
  resources:
  - namespaces
  - resourcequotas
  - nodes
  - pods
  verbs:
  - get
  - list
- apiGroups:
    - metrics.k8s.io
  resources:
    - pods
    - nodes
  verbs:
    - get
    - list
