apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8scapcity
  namespace: k8scapcity
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8scapcity
  template:
    metadata:
      labels:
        app: k8scapcity
    spec:
      containers:
        - name: k8scapcity
          image: 'hub.soh.re/k8scapcity:v0.2.1'
          env:
          - name: NODELABEL
            value: node-role.kubernetes.io/compute=true
          resources:
            limits:
              cpu: "1"
              memory: 1Gi
            requests:
              cpu: 200m
              memory: 200Mi
      serviceAccount: k8scapcity
      serviceAccountName: k8scapcity
